# Generated by Django 5.2.7 on 2025-10-19 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transaction_type_category_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Meta')),
                ('goal_type', models.CharField(choices=[('spending_limit', 'Limite de Gasto'), ('saving_goal', 'Meta de Economia')], max_length=15, verbose_name='Tipo da Meta')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Alvo')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Atual (Economia)')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'type': 'expense'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
