# Generated by Django 5.2.7 on 2025-10-20 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_budgetgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurrence_interval',
            field=models.CharField(blank=True, choices=[('monthly', 'Mensal')], max_length=20, null=True),
        ),
    ]
